dependencies:
# - <organization/repo>@<version>
- smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      -'@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: "0x19a37a3c822447ffb80c2732b8c8eb9b"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '	0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
  kovan:
  mainnet:
wallets:
   from_key: ${PRIVATE_KEY} 
